In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv('01_Contract_data.csv')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          51301 non-null  int64
 1   Member_ID      51301 non-null  int64
 2   Sales_Type     51301 non-null  object
 3   Contract_Type  51301 non-null  object
 4   Channel        51301 non-null  object
 5   Datetime       51301 non-null  object
 6   Term           51301 non-null  int64
 7   Payment_Type   51301 non-null  object
 8   Product_Type   51301 non-null  object
 9   Amount_Month   51301 non-null  int64
 10  Customer_Type  51299 non-null  object
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object
 13  Address2       51299 non-null  object
 14  State          51301 non-null  object
 15  Overdue_count  51301 non-null  int64
 16  Overdue_Type   51301 non-null  object
 17  Gender         51301 non-null  object
 18  Credit_Rank    42520 non-null  float64
 19  Bank           48542 non-null  object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.8+ MB

# 데이터 추출

In [7]:
# 행 단위 데이터 추출
df1.head() # 상위 5개 데이터 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합

In [8]:
df1.tail() # 하위 5개 데이터 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

In [12]:
df2 = df1.head(50) # 상위 50개 데이터 추출, 즉 head() 괄호 안에 숫자로 정할 수 있음

In [13]:
df2

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
5,6,66165241,렌탈,프로모션계약,영업방판,2019-07-29,60,CMS,DES-3A,90900,개인,53.0,경상도,경상도,계약확정,0,없음,여자,5.0,농협중앙회
6,7,66751017,렌탈,패키지계약,홈쇼핑/방송,2019-01-30,60,카드이체,DES-1,98400,개인,66.0,경상도,경상도,계약확정,0,없음,남자,1.0,롯데카드
7,8,66751017,렌탈,패키지계약,홈쇼핑/방송,2019-01-17,60,카드이체,DES-2,80400,개인,66.0,경상도,경상도,계약확정,0,없음,남자,1.0,롯데카드
8,9,66758007,렌탈,일반계약,영업방판,2019-06-30,60,카드이체,DES-3A,102900,개인,62.0,경상도,경상도,계약확정,0,없음,여자,2.0,롯데카드
9,10,66756702,렌탈,프로모션계약,영업방판,2019-06-30,60,CMS,DES-1,105900,개인,51.0,경상도,경상도,계약확정,0,없음,여자,1.0,신한은행
10,11,66757254,렌탈,패키지계약,홈쇼핑/방송,2019-07-23,60,카드이체,DES-1,81900,개인,39.0,경상도,경상도,계약확정,0,없음,여자,1.0,국민카드
11,12,66757254,렌탈,패키지계약,홈쇼핑/방송,2019-08-09,60,카드이체,DES-2,81900,개인,39.0,경상도,경상도,계약확정,0,없음,여자,1.0,국민카드
12,13,66355286,렌탈,프로모션계약,영업방판,2020-02-10,60,카드이체,DES-3A,90900,개인,35.0,경상도,경상도,계약확정,0,없음,여자,7.0,현대카드
13,14,66757861,렌탈,일반계약,영업방판,2020-02-10,60,CMS,DES-1,96900,개인,50.0,경상도,경상도,계약확정,0,없음,남자,1.0,농협중앙회
14,15,66758085,렌탈,프로모션계약,영업방판,2020-07-11,60,CMS,DES-2,90900,개인,48.0,경상도,경상도,계약확정,0,없음,남자,1.0,농협회원조합
15,16,66423049,멤버십,멤버십3유형,재계약,2019-04-29,12,CMS,DES-1,66900,개인,59.0,전라도,전라도,계약확정,0,없음,여자,2.0,농협회원조합
16,17,66190995,렌탈,프로모션계약,홈쇼핑/방송,2019-06-25,60,카드이체,DES-1,96900,개인,61.0,경상도,부산광역시,계약확정,0,없음,남자,1.0,롯데카드
17,18,66757035,렌탈,프로모션계약,전문매장H,2019-09-28,60,CMS,DES-1,96900,개인,32.0,경상도,부산광역시,해약확정,0,없음,여자,4.0,부산은행
18,19,66423249,멤버십,멤버십3유형,재계약,2020-01-17,12,CMS,DES-1,66900,개인,87.0,경상도,부산광역시,계약확정,0,없음,여자,2.0,농협중앙회
19,20,66755490,렌탈,프로모션계약,영업방판,2020-01-17,60,카드이체,DES-1,105900,개인,58.0,경상도,부산광역시,계약확정,0,없음,여자,1.0,롯데카드
20,21,66423230,멤버십,멤버십3유형,재계약,2020-04-02,12,CMS,DES-1,66900,개인,43.0,경상도,부산광역시,계약확정,0,없음,여자,2.0,우리은행
21,22,66758336,렌탈,프로모션계약,전문매장Z,2020-04-25,60,CMS,DES-1,111900,개인,72.0,경상도,부산광역시,계약확정,0,없음,남자,9.0,농협회원조합
22,23,66758074,렌탈,일반계약,영업방판,2020-07-23,60,CMS,DES-1,96900,개인,NaN,충청도,충청도,계약확정,0,없음,여자,1.0,농협중앙회
23,24,66758074,렌탈,일반계약,영업방판,2019-01-01,60,CMS,DES-2,87900,개인,NaN,충청도,충청도,계약확정,0,없음,여자,1.0,농협중앙회
24,25,66755833,렌탈,패키지계약,전문매장Z,2019-01-21,60,CMS,DES-1,134700,개인,40.0,충청도,충청도,계약확정,0,없음,여자,7.0,우체국
25,26,66755833,렌탈,패키지계약,전문매장Z,2019-01-29,60,CMS,DES-2,89400,개인,40.0,충청도,충청도,계약확정,0,없음,여자,7.0,우체국
26,27,66422938,멤버십,멤버십3유형,재계약,2019-02-12,12,CMS,DES-1,66900,개인,73.0,강원도,강원도,계약확정,0,없음,여자,2.0,신한은행
27,28,66755125,렌탈,프로모션계약,홈쇼핑/방송,2019-02-24,60,카드이체,DES-1,105900,개인,50.0,경기도,경기도,계약확정,0,없음,여자,1.0,롯데카드
28,29,66422513,멤버십,멤버십3유형,재계약,2019-03-15,12,CMS,DES-1,66900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,2.0,농협회원조합
29,30,66419239,렌탈,교체계약,영업방판,2019-04-08,60,CMS,DES-1,96900,개인,38.0,경기도,경기도,계약확정,0,없음,여자,NaN,국민은행
30,31,25702131,멤버십,멤버십3유형,재계약,2019-04-28,12,CMS,DES-1,66900,사업자,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,기업은행
31,32,66422449,멤버십,멤버십3유형,재계약,2019-05-31,12,CMS,DES-1,66900,개인,51.0,경기도,경기도,계약확정,0,없음,여자,1.0,농협중앙회
32,33,25742841,렌탈,프로모션계약,영업방판,2019-08-10,60,CMS,DES-1,142200,사업자,57.0,경기도,경기도,계약확정,0,없음,여자,NaN,농협회원조합
33,34,66758615,렌탈,프로모션계약,대형마트H,2019-08-21,60,CMS,DES-1,96900,개인,48.0,서울특별시,서울특별시,계약확정,0,없음,남자,7.0,농협중앙회
34,35,66758778,렌탈,일반계약,홈쇼핑/방송,2019-09-03,60,CMS,DES-1,96900,개인,59.0,서울특별시,서울특별시,계약확정,0,없음,여자,5.0,우리은행
35,36,25742683,렌탈,프로모션계약,대형마트E,2019-10-05,60,CMS,DES-3A,102900,사업자,48.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,신한은행
36,37,66127796,렌탈,프로모션계약,영업방판,2019-11-26,60,CMS,DES-2,90900,개인,43.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,우리은행
37,38,25851817,멤버십,멤버십3유형,재계약,2020-01-23,12,CMS,DES-1,96600,사업자,NaN,서울특별시,서울특별시,해약확정,0,없음,여자,NaN,국민은행
38,39,66528773,렌탈,일반계약,홈쇼핑/방송,2020-04-11,60,CMS,DES-1,96900,개인,48.0,서울특별시,서울특별시,계약확정,0,없음,남자,3.0,국민은행
39,40,25742687,렌탈,프로모션계약,영업방판,2020-07-24,60,CMS,DES-1,142200,사업자,63.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,SC제일은행
40,41,25742687,렌탈,일반계약,영업방판,2019-06-18,60,CMS,DES-2,96900,사업자,63.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,SC제일은행
41,42,25742687,렌탈,일반계약,영업방판,2019-08-02,60,CMS,DES-2,96900,사업자,63.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,SC제일은행
42,43,66758315,렌탈,프로모션계약,영업방판,2019-09-06,60,CMS,DES-1,105900,개인,29.0,서울특별시,서울특별시,계약확정,0,없음,여자,6.0,우리은행
43,44,66758224,렌탈,프로모션계약,영업방판,2019-09-07,60,CMS,DES-1,105900,개인,57.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,우리은행
44,45,66211709,렌탈,교체계약,영업방판,2019-12-19,60,CMS,DES-1,96900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,남자,4.0,농협회원조합
45,46,66135112,렌탈,교체계약,영업방판,2019-06-20,60,CMS,DES-1,96900,개인,51.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,신한은행
46,47,66758431,렌탈,일반계약,홈쇼핑/방송,2019-02-27,60,카드이체,DES-1,96900,개인,62.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,국민카드
47,48,66423714,멤버십,멤버십3유형,재계약,2019-02-27,12,CMS,DES-1,66900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,남자,3.0,농협중앙회
48,49,66754342,렌탈,패키지계약,홈쇼핑/방송,2019-01-08,60,카드이체,DES-1,98400,개인,37.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,현대카드
49,50,66754342,렌탈,패키지계약,홈쇼핑/방송,2019-02-28,60,카드이체,DES-2,80400,개인,37.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,현대카드

In [15]:
df1.iloc[100:200] # 원하는 범위의 데이터를 추출, iloc 함수는 특이하게 대괄호를 사용한다.

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
100,101,66758264,렌탈,패키지계약,홈쇼핑/방송,2019-01-01,60,CMS,DES-1,81900,개인,38.0,전라도,광주광역시,계약확정,0,없음,남자,2.0,광주은행
101,102,66758264,렌탈,패키지계약,홈쇼핑/방송,2019-02-09,60,CMS,DES-2,81900,개인,38.0,전라도,광주광역시,계약확정,0,없음,남자,2.0,광주은행
102,103,66758918,렌탈,일반계약,전문매장H,2019-01-31,60,CMS,DES-1,96900,개인,36.0,전라도,광주광역시,계약확정,0,없음,여자,1.0,국민은행
103,104,66437196,렌탈,프로모션계약,영업방판,2019-01-31,60,CMS,DES-3A,90900,개인,44.0,전라도,광주광역시,계약확정,0,없음,여자,2.0,농협회원조합
104,105,66420849,렌탈,프로모션계약,영업방판,2019-02-21,60,CMS,DES-2,90900,개인,50.0,전라도,광주광역시,계약확정,0,없음,남자,3.0,외환은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,66758799,렌탈,패키지계약,홈쇼핑/방송,2019-02-19,60,카드이체,DES-2,81900,개인,49.0,경상도,부산광역시,계약확정,0,없음,남자,1.0,롯데카드
196,197,66331658,렌탈,교체계약,영업방판,2019-02-19,60,CMS,DES-1,102900,개인,52.0,경상도,부산광역시,계약확정,0,없음,남자,NaN,농협중앙회
197,198,66758349,렌탈,일반계약,영업방판,2019-12-17,60,CMS,DES-1,96900,개인,64.0,경상도,부산광역시,계약확정,0,없음,여자,2.0,국민은행
198,199,66464668,렌탈,일반계약,영업방판,2020-06-23,60,CMS,DES-2,87900,개인,63.0,경상도,울산광역시,계약확정,0,없음,여자,1.0,농협중앙회
199,200,66635455,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-3A,90900,개인,39.0,경상도,대구광역시,계약확정,0,없음,여자,NaN,농협회원조합

In [17]:
df1.iloc[:50] # df1.head(50)과 같은 결과를 내온다.

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
5,6,66165241,렌탈,프로모션계약,영업방판,2019-07-29,60,CMS,DES-3A,90900,개인,53.0,경상도,경상도,계약확정,0,없음,여자,5.0,농협중앙회
6,7,66751017,렌탈,패키지계약,홈쇼핑/방송,2019-01-30,60,카드이체,DES-1,98400,개인,66.0,경상도,경상도,계약확정,0,없음,남자,1.0,롯데카드
7,8,66751017,렌탈,패키지계약,홈쇼핑/방송,2019-01-17,60,카드이체,DES-2,80400,개인,66.0,경상도,경상도,계약확정,0,없음,남자,1.0,롯데카드
8,9,66758007,렌탈,일반계약,영업방판,2019-06-30,60,카드이체,DES-3A,102900,개인,62.0,경상도,경상도,계약확정,0,없음,여자,2.0,롯데카드
9,10,66756702,렌탈,프로모션계약,영업방판,2019-06-30,60,CMS,DES-1,105900,개인,51.0,경상도,경상도,계약확정,0,없음,여자,1.0,신한은행
10,11,66757254,렌탈,패키지계약,홈쇼핑/방송,2019-07-23,60,카드이체,DES-1,81900,개인,39.0,경상도,경상도,계약확정,0,없음,여자,1.0,국민카드
11,12,66757254,렌탈,패키지계약,홈쇼핑/방송,2019-08-09,60,카드이체,DES-2,81900,개인,39.0,경상도,경상도,계약확정,0,없음,여자,1.0,국민카드
12,13,66355286,렌탈,프로모션계약,영업방판,2020-02-10,60,카드이체,DES-3A,90900,개인,35.0,경상도,경상도,계약확정,0,없음,여자,7.0,현대카드
13,14,66757861,렌탈,일반계약,영업방판,2020-02-10,60,CMS,DES-1,96900,개인,50.0,경상도,경상도,계약확정,0,없음,남자,1.0,농협중앙회
14,15,66758085,렌탈,프로모션계약,영업방판,2020-07-11,60,CMS,DES-2,90900,개인,48.0,경상도,경상도,계약확정,0,없음,남자,1.0,농협회원조합
15,16,66423049,멤버십,멤버십3유형,재계약,2019-04-29,12,CMS,DES-1,66900,개인,59.0,전라도,전라도,계약확정,0,없음,여자,2.0,농협회원조합
16,17,66190995,렌탈,프로모션계약,홈쇼핑/방송,2019-06-25,60,카드이체,DES-1,96900,개인,61.0,경상도,부산광역시,계약확정,0,없음,남자,1.0,롯데카드
17,18,66757035,렌탈,프로모션계약,전문매장H,2019-09-28,60,CMS,DES-1,96900,개인,32.0,경상도,부산광역시,해약확정,0,없음,여자,4.0,부산은행
18,19,66423249,멤버십,멤버십3유형,재계약,2020-01-17,12,CMS,DES-1,66900,개인,87.0,경상도,부산광역시,계약확정,0,없음,여자,2.0,농협중앙회
19,20,66755490,렌탈,프로모션계약,영업방판,2020-01-17,60,카드이체,DES-1,105900,개인,58.0,경상도,부산광역시,계약확정,0,없음,여자,1.0,롯데카드
20,21,66423230,멤버십,멤버십3유형,재계약,2020-04-02,12,CMS,DES-1,66900,개인,43.0,경상도,부산광역시,계약확정,0,없음,여자,2.0,우리은행
21,22,66758336,렌탈,프로모션계약,전문매장Z,2020-04-25,60,CMS,DES-1,111900,개인,72.0,경상도,부산광역시,계약확정,0,없음,남자,9.0,농협회원조합
22,23,66758074,렌탈,일반계약,영업방판,2020-07-23,60,CMS,DES-1,96900,개인,NaN,충청도,충청도,계약확정,0,없음,여자,1.0,농협중앙회
23,24,66758074,렌탈,일반계약,영업방판,2019-01-01,60,CMS,DES-2,87900,개인,NaN,충청도,충청도,계약확정,0,없음,여자,1.0,농협중앙회
24,25,66755833,렌탈,패키지계약,전문매장Z,2019-01-21,60,CMS,DES-1,134700,개인,40.0,충청도,충청도,계약확정,0,없음,여자,7.0,우체국
25,26,66755833,렌탈,패키지계약,전문매장Z,2019-01-29,60,CMS,DES-2,89400,개인,40.0,충청도,충청도,계약확정,0,없음,여자,7.0,우체국
26,27,66422938,멤버십,멤버십3유형,재계약,2019-02-12,12,CMS,DES-1,66900,개인,73.0,강원도,강원도,계약확정,0,없음,여자,2.0,신한은행
27,28,66755125,렌탈,프로모션계약,홈쇼핑/방송,2019-02-24,60,카드이체,DES-1,105900,개인,50.0,경기도,경기도,계약확정,0,없음,여자,1.0,롯데카드
28,29,66422513,멤버십,멤버십3유형,재계약,2019-03-15,12,CMS,DES-1,66900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,2.0,농협회원조합
29,30,66419239,렌탈,교체계약,영업방판,2019-04-08,60,CMS,DES-1,96900,개인,38.0,경기도,경기도,계약확정,0,없음,여자,NaN,국민은행
30,31,25702131,멤버십,멤버십3유형,재계약,2019-04-28,12,CMS,DES-1,66900,사업자,NaN,경기도,경기도,계약확정,0,없음,여자,NaN,기업은행
31,32,66422449,멤버십,멤버십3유형,재계약,2019-05-31,12,CMS,DES-1,66900,개인,51.0,경기도,경기도,계약확정,0,없음,여자,1.0,농협중앙회
32,33,25742841,렌탈,프로모션계약,영업방판,2019-08-10,60,CMS,DES-1,142200,사업자,57.0,경기도,경기도,계약확정,0,없음,여자,NaN,농협회원조합
33,34,66758615,렌탈,프로모션계약,대형마트H,2019-08-21,60,CMS,DES-1,96900,개인,48.0,서울특별시,서울특별시,계약확정,0,없음,남자,7.0,농협중앙회
34,35,66758778,렌탈,일반계약,홈쇼핑/방송,2019-09-03,60,CMS,DES-1,96900,개인,59.0,서울특별시,서울특별시,계약확정,0,없음,여자,5.0,우리은행
35,36,25742683,렌탈,프로모션계약,대형마트E,2019-10-05,60,CMS,DES-3A,102900,사업자,48.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,신한은행
36,37,66127796,렌탈,프로모션계약,영업방판,2019-11-26,60,CMS,DES-2,90900,개인,43.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,우리은행
37,38,25851817,멤버십,멤버십3유형,재계약,2020-01-23,12,CMS,DES-1,96600,사업자,NaN,서울특별시,서울특별시,해약확정,0,없음,여자,NaN,국민은행
38,39,66528773,렌탈,일반계약,홈쇼핑/방송,2020-04-11,60,CMS,DES-1,96900,개인,48.0,서울특별시,서울특별시,계약확정,0,없음,남자,3.0,국민은행
39,40,25742687,렌탈,프로모션계약,영업방판,2020-07-24,60,CMS,DES-1,142200,사업자,63.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,SC제일은행
40,41,25742687,렌탈,일반계약,영업방판,2019-06-18,60,CMS,DES-2,96900,사업자,63.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,SC제일은행
41,42,25742687,렌탈,일반계약,영업방판,2019-08-02,60,CMS,DES-2,96900,사업자,63.0,서울특별시,서울특별시,계약확정,0,없음,여자,NaN,SC제일은행
42,43,66758315,렌탈,프로모션계약,영업방판,2019-09-06,60,CMS,DES-1,105900,개인,29.0,서울특별시,서울특별시,계약확정,0,없음,여자,6.0,우리은행
43,44,66758224,렌탈,프로모션계약,영업방판,2019-09-07,60,CMS,DES-1,105900,개인,57.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,우리은행
44,45,66211709,렌탈,교체계약,영업방판,2019-12-19,60,CMS,DES-1,96900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,남자,4.0,농협회원조합
45,46,66135112,렌탈,교체계약,영업방판,2019-06-20,60,CMS,DES-1,96900,개인,51.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,신한은행
46,47,66758431,렌탈,일반계약,홈쇼핑/방송,2019-02-27,60,카드이체,DES-1,96900,개인,62.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,국민카드
47,48,66423714,멤버십,멤버십3유형,재계약,2019-02-27,12,CMS,DES-1,66900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,남자,3.0,농협중앙회
48,49,66754342,렌탈,패키지계약,홈쇼핑/방송,2019-01-08,60,카드이체,DES-1,98400,개인,37.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,현대카드
49,50,66754342,렌탈,패키지계약,홈쇼핑/방송,2019-02-28,60,카드이체,DES-2,80400,개인,37.0,서울특별시,서울특별시,계약확정,0,없음,남자,5.0,현대카드

In [19]:
df1.iloc[50000:] # 50000번째부터 끝까지의 데이터 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
50000,50002,66797406,렌탈,패키지계약,대형마트A,2019-02-23,60,CMS,DES-2,89400,개인,NaN,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,국민은행
50001,50003,66798217,렌탈,프로모션계약,영업방판,2019-02-23,60,카드이체,DES-1,105900,개인,NaN,경기도,경기도,계약확정,0,없음,남자,3.0,롯데카드
50002,50004,66266827,렌탈,프로모션계약,대형마트A,2019-05-23,60,CMS,DES-2,90900,개인,58.0,경기도,경기도,계약확정,0,없음,여자,2.0,우리은행
50003,50005,66798642,렌탈,프로모션계약,영업방판,2019-02-23,60,카드이체,DES-1,105900,개인,NaN,경기도,경기도,계약확정,0,없음,여자,4.0,롯데카드
50004,50006,66797821,렌탈,일반계약,대형마트E,2019-02-23,60,CMS,DES-1,96900,개인,NaN,경기도,경기도,계약확정,0,없음,여자,1.0,국민은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고
51298,51300,66799197,렌탈,프로모션계약,영업방판,2019-04-01,39,카드이체,ERA,120900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,롯데카드
51299,51301,66792778,렌탈,일반계약,홈쇼핑/방송,2020-02-06,60,카드이체,DES-1,96900,개인,54.0,서울특별시,서울특별시,계약확정,0,없음,여자,2.0,롯데카드
51300,51302,66799607,렌탈,일반계약,홈쇼핑/방송,2019-04-24,60,CMS,DES-1,96900,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,여자,8.0,신한은행

In [20]:
# 열 단위 데이터 추출
df1['Age'] # Series 형태로 데이터 추출

0        42.0
1        39.0
2        48.0
3        39.0
4        60.0
         ...
51296    47.0
51297    42.0
51298    65.0
51299    54.0
51300    53.0
Name: Age, Length: 51301, dtype: float64

In [22]:
df1[['Age']] # 데이터 프레임 형태로 데이터 추출

        Age
0      42.0
1      39.0
2      48.0
3      39.0
4      60.0
...     ...
51296  47.0
51297  42.0
51298  65.0
51299  54.0
51300  53.0

[51301 rows x 1 columns]

In [25]:
# Series 형태는 index - Value (순서-값) 데이터가 구성
# 2개 이상의 Column이 올 때는 데이터 프레임 형태로 추출 해야한다.
df3 = df1[['Sales_Type','Contract_Type','Amount_Month']]

In [27]:
df3

      Sales_Type Contract_Type  Amount_Month
0             렌탈          일반계약         96900
1             렌탈          교체계약        102900
2             렌탈          일반계약         96900
3            멤버십        멤버십3유형         66900
4            멤버십        멤버십3유형         66900
...          ...           ...           ...
51296         렌탈        프로모션계약         96900
51297         렌탈          일반계약         96900
51298         렌탈        프로모션계약        120900
51299         렌탈          일반계약         96900
51300         렌탈          일반계약         96900

[51301 rows x 3 columns]

In [28]:
df3.head(100)

   Sales_Type Contract_Type  Amount_Month
0          렌탈          일반계약         96900
1          렌탈          교체계약        102900
2          렌탈          일반계약         96900
3         멤버십        멤버십3유형         66900
4         멤버십        멤버십3유형         66900
..        ...           ...           ...
95         렌탈        프로모션계약         90900
96         렌탈          일반계약         96900
97         렌탈        프로모션계약         96900
98         렌탈        프로모션계약         96900
99        멤버십        멤버십3유형         75900

[100 rows x 3 columns]

In [30]:
df4 = df1[['Product_Type','Bank']].head(1000)

In [31]:
df4

    Product_Type    Bank
0          DES-1   새마을금고
1          DES-1    현대카드
2          DES-1    우리은행
3          DES-1  농협회원조합
4          DES-1  농협회원조합
..           ...     ...
995        DES-1    BC카드
996        DES-1    롯데카드
997        DES-1     NaN
998        DES-1    신한은행
999        DES-1    삼성카드

[1000 rows x 2 columns]

In [32]:
df5 = df1[['Member_ID','Channel','Sales_Type']]

In [33]:
df5

       Member_ID Channel Sales_Type
0       66758234    영업방판         렌탈
1       66755948    영업방판         렌탈
2       66756657  홈쇼핑/방송         렌탈
3       66423450     재계약        멤버십
4       66423204     재계약        멤버십
...          ...     ...        ...
51296   66579515   대형마트A         렌탈
51297   66799558   대형마트A         렌탈
51298   66799197    영업방판         렌탈
51299   66792778  홈쇼핑/방송         렌탈
51300   66799607  홈쇼핑/방송         렌탈

[51301 rows x 3 columns]

In [34]:
df5.head(100)

    Member_ID Channel Sales_Type
0    66758234    영업방판         렌탈
1    66755948    영업방판         렌탈
2    66756657  홈쇼핑/방송         렌탈
3    66423450     재계약        멤버십
4    66423204     재계약        멤버십
..        ...     ...        ...
95   25751808    영업방판         렌탈
96   66758771    영업방판         렌탈
97   66677887    영업방판         렌탈
98   66758748   전문매장H         렌탈
99   66423756     재계약        멤버십

[100 rows x 3 columns]