In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv('01_Contract_data.csv')

In [4]:
df1.head(3)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행

In [5]:
df1['Contract_Type'].value_counts()

프로모션계약    15811
일반계약      15321
패키지계약     10186
교체계약       4975
멤버십3유형     2627
멤버십2유형     2086
단체계약        190
멤버십4유형       92
멤버십1유형       13
Name: Contract_Type, dtype: int64

In [7]:
# Contract_Type이 교체계약인 데이터만 필터링
condition1 = df1['Contract_Type']=='교체계약'

In [8]:
condition1

0        False
1         True
2        False
3        False
4        False
         ...
51296    False
51297    False
51298    False
51299    False
51300    False
Name: Contract_Type, Length: 51301, dtype: bool

In [10]:
df1.loc[condition1]

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
29,30,66419239,렌탈,교체계약,영업방판,2019-04-08,60,CMS,DES-1,96900,개인,38.0,경기도,경기도,계약확정,0,없음,여자,NaN,국민은행
44,45,66211709,렌탈,교체계약,영업방판,2019-12-19,60,CMS,DES-1,96900,개인,65.0,서울특별시,서울특별시,계약확정,0,없음,남자,4.0,농협회원조합
45,46,66135112,렌탈,교체계약,영업방판,2019-06-20,60,CMS,DES-1,96900,개인,51.0,서울특별시,서울특별시,계약확정,0,없음,여자,1.0,신한은행
55,56,25856039,렌탈,교체계약,영업방판,2019-05-01,60,CMS,DES-1,96900,사업자,NaN,경상도,부산광역시,계약확정,0,없음,여자,NaN,농협중앙회
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51232,51234,66231054,렌탈,교체계약,영업방판,2019-03-07,60,CMS,DES-1,96900,개인,40.0,경상도,울산광역시,계약확정,0,없음,남자,1.0,경남은행
51273,51275,66814025,렌탈,교체계약,대형마트A,2019-10-23,60,CMS,DES-1,96900,개인,39.0,충청도,대전광역시,계약확정,0,없음,여자,1.0,신한은행
51283,51285,66387839,렌탈,교체계약,대형마트A,2019-07-31,60,CMS,DES-1,96900,개인,49.0,경상도,부산광역시,계약확정,0,없음,여자,NaN,하나은행
51287,51289,66444051,렌탈,교체계약,대형마트A,2019-09-29,60,CMS,DES-1,102900,개인,90.0,서울특별시,서울특별시,계약확정,0,없음,남자,NaN,신한은행
51289,51291,66441028,렌탈,교체계약,대형마트A,2020-01-16,60,CMS,DES-2,78900,개인,56.0,경기도,경기도,계약확정,0,없음,남자,1.0,롯데카드

In [11]:
# Amount_Month 1500000 이상인 데이터만 필터링

cond2 = df1['Amount_Month'] >= 150000
df1.loc[cond2]

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
205,206,25777820,렌탈,프로모션계약,직영유통사,2019-03-25,36,가상계좌,DES-1,180750,사업자,NaN,경기도,경기도,계약확정,1,있음,여자,NaN,NaN
206,207,25777820,렌탈,프로모션계약,직영유통사,2019-03-25,36,가상계좌,DES-1,180750,사업자,NaN,경기도,경기도,계약확정,1,있음,여자,NaN,NaN
207,208,25777820,렌탈,프로모션계약,직영유통사,2019-01-05,36,가상계좌,DES-1,180750,사업자,NaN,경기도,경기도,계약확정,1,있음,여자,NaN,NaN
233,234,66758193,렌탈,프로모션계약,영업방판,2019-05-08,39,카드이체,MMC,185700,개인,54.0,충청도,충청도,계약확정,0,없음,남자,6.0,롯데카드
328,329,25742694,렌탈,프로모션계약,대형마트E,2020-03-06,39,CMS,MMC,185700,사업자,NaN,경기도,인천광역시,계약확정,0,없음,여자,NaN,기업은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50381,50383,66798387,렌탈,프로모션계약,영업방판,2019-02-24,39,카드이체,MMC,185700,개인,37.0,경기도,경기도,계약확정,0,없음,남자,3.0,롯데카드
50464,50466,66758303,렌탈,프로모션계약,대형마트A,2019-04-03,39,CMS,MMC,185700,개인,53.0,서울특별시,서울특별시,계약확정,0,없음,남자,1.0,국민은행
50752,50754,66798515,렌탈,프로모션계약,영업방판,2019-02-28,39,CMS,MMC,185700,개인,37.0,서울특별시,서울특별시,계약확정,8,있음,남자,6.0,농협회원조합
50951,50953,25736066,렌탈,프로모션계약,영업방판,2020-07-24,39,CMS,MMC,185700,사업자,NaN,서울특별시,서울특별시,계약확정,8,있음,여자,NaN,신한은행
51187,51189,66799273,렌탈,프로모션계약,전단홍보,2019-06-09,39,CMS,MMC,185700,개인,58.0,전라도,광주광역시,계약확정,0,없음,남자,NaN,농협중앙회

In [12]:
cond2

0        False
1        False
2        False
3        False
4        False
         ...
51296    False
51297    False
51298    False
51299    False
51300    False
Name: Amount_Month, Length: 51301, dtype: bool

In [13]:
# Overdue_count(연체건수) 가 5회 이상인 데이터만 필터이

cond3 = (df1['Overdue_count'] >= 5)
cond3

0        False
1        False
2        False
3        False
4         True
         ...
51296    False
51297    False
51298    False
51299    False
51300    False
Name: Overdue_count, Length: 51301, dtype: bool

In [15]:
df2 = df1.loc[cond3]

In [16]:
df2

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
61,62,66758851,렌탈,일반계약,영업방판,2019-01-04,60,CMS,DES-R4,126900,개인,27.0,경기도,인천광역시,계약확정,12,있음,남자,5.0,농협중앙회
95,96,25751808,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-3A,90900,사업자,NaN,경기도,경기도,계약확정,15,있음,여자,NaN,기업은행
341,342,66758501,렌탈,프로모션계약,영업방판,2019-01-02,39,카드이체,ERA,120900,개인,38.0,경상도,부산광역시,계약확정,15,있음,여자,8.0,국민카드
347,348,66689896,렌탈,프로모션계약,영업방판,2020-07-22,60,CMS,DES-2,90900,개인,55.0,서울특별시,서울특별시,계약확정,15,있음,여자,7.0,신한은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51044,51046,66796493,렌탈,프로모션계약,대형마트A,2019-02-24,60,CMS,DES-1,105900,개인,35.0,서울특별시,서울특별시,계약확정,5,있음,남자,NaN,국민은행
51145,51147,25731398,렌탈,프로모션계약,영업방판,2019-12-19,60,CMS,DES-3A,108900,사업자,NaN,경기도,인천광역시,계약확정,11,있음,여자,NaN,국민은행
51175,51177,66798828,렌탈,프로모션계약,전문매장H,2019-03-19,60,CMS,DES-1,96900,개인,49.0,경상도,대구광역시,계약확정,11,있음,남자,7.0,대구은행
51176,51178,66787756,렌탈,프로모션계약,영업방판,2019-07-07,39,CMS,ERA,126900,개인,NaN,충청도,충청도,계약확정,11,있음,여자,NaN,농협회원조합
51291,51293,25731743,렌탈,일반계약,영업방판,2020-02-12,60,CMS,DES-3A,102900,사업자,NaN,경기도,경기도,계약확정,10,있음,여자,NaN,농협중앙회

In [22]:
# Address1 가 경기도 이면서, Overdue_count 연체건수가 5회 이상인 데이터 필터링

cond4 = (df1['Address1']== '경기도')
cond5 = (df1['Overdue_count'] >= 5)
df1.loc[cond4 & cond5] #cond4 조건도 만족하면서 cond5 조건도 만족하는 데이터 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
61,62,66758851,렌탈,일반계약,영업방판,2019-01-04,60,CMS,DES-R4,126900,개인,27.0,경기도,인천광역시,계약확정,12,있음,남자,5.0,농협중앙회
95,96,25751808,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-3A,90900,사업자,NaN,경기도,경기도,계약확정,15,있음,여자,NaN,기업은행
633,634,66697051,렌탈,프로모션계약,영업방판,2019-01-28,60,CMS,DES-2,90900,개인,NaN,경기도,경기도,계약확정,11,있음,남자,9.0,농협회원조합
900,901,66759324,렌탈,패키지계약,홈쇼핑/방송,2019-10-25,60,CMS,DES-1,81900,개인,46.0,경기도,경기도,계약확정,13,있음,여자,8.0,우리은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50383,50385,66798413,렌탈,프로모션계약,대형마트A,2019-06-25,60,CMS,DES-1,105900,개인,NaN,경기도,경기도,계약확정,12,있음,여자,8.0,농협회원조합
50808,50810,66218985,멤버십,멤버십3유형,대형마트A,2020-03-05,12,CMS,DES-1,66900,개인,47.0,경기도,인천광역시,계약확정,11,있음,여자,NaN,우체국
50931,50933,66798617,렌탈,일반계약,영업방판,2019-06-20,60,CMS,DES-1,108900,개인,NaN,경기도,경기도,계약확정,10,있음,여자,9.0,농협회원조합
51145,51147,25731398,렌탈,프로모션계약,영업방판,2019-12-19,60,CMS,DES-3A,108900,사업자,NaN,경기도,인천광역시,계약확정,11,있음,여자,NaN,국민은행
51291,51293,25731743,렌탈,일반계약,영업방판,2020-02-12,60,CMS,DES-3A,102900,사업자,NaN,경기도,경기도,계약확정,10,있음,여자,NaN,농협중앙회

In [24]:
#연령대가 30세 미만, 연체건수 5회 미만

cond6 = (df1['Age'] < 30)
cond7 = (df1['Overdue_count'] >= 5)
df1.loc[cond6 & cond7].head(10)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
61,62,66758851,렌탈,일반계약,영업방판,2019-01-04,60,CMS,DES-R4,126900,개인,27.0,경기도,인천광역시,계약확정,12,있음,남자,5.0,농협중앙회
1345,1346,66758268,렌탈,패키지계약,영업방판,2019-09-17,60,CMS,DES-2,89400,개인,28.0,경상도,경상도,계약확정,10,있음,남자,4.0,경남은행
1594,1595,66758268,렌탈,일반계약,영업방판,2020-02-12,60,CMS,DES-2,105900,개인,28.0,경상도,경상도,계약확정,5,있음,남자,4.0,경남은행
5845,5846,66762531,렌탈,패키지계약,영업방판,2020-07-10,60,CMS,DES-1,134400,개인,27.0,충청도,대전광역시,계약확정,15,있음,남자,5.0,하나은행
5846,5847,66762531,렌탈,패키지계약,영업방판,2020-07-29,60,CMS,DES-2,89400,개인,27.0,충청도,대전광역시,계약확정,15,있음,남자,5.0,하나은행
6318,6319,66762154,렌탈,프로모션계약,영업방판,2019-01-12,39,CMS,ERA,120900,개인,29.0,경기도,경기도,계약확정,7,있음,여자,8.0,신한은행
7741,7742,66762293,렌탈,패키지계약,홈쇼핑/방송,2019-04-12,60,CMS,DES-1,81900,개인,29.0,전라도,광주광역시,계약확정,5,있음,여자,7.0,새마을금고
7742,7743,66762293,렌탈,패키지계약,홈쇼핑/방송,2019-04-13,60,CMS,DES-2,81900,개인,29.0,전라도,광주광역시,계약확정,5,있음,여자,7.0,새마을금고
7789,7790,66763046,렌탈,프로모션계약,대형마트E,2019-05-28,60,CMS,DES-1,96900,개인,29.0,경기도,경기도,계약확정,5,있음,남자,NaN,우리은행
9638,9639,66521212,렌탈,프로모션계약,영업방판,2019-01-15,60,CMS,DES-3A,90900,개인,29.0,경기도,경기도,계약확정,14,있음,남자,5.0,농협중앙회

In [28]:
# Address1가 경기도 이거나 충청도인 고객 데이터 필터링

cond8 = (df1['Address1']=='경기도')
cond9 = (df1['Address1']=='충청도')
df1.loc[cond8 | cond9] #cond8 조건을 만족하거나 cond9 조건을 만족하는 데이터를 모두 추출

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51293,51295,66799369,렌탈,일반계약,대형마트A,2020-07-10,60,CMS,DES-1,96900,개인,74.0,경기도,경기도,계약확정,0,없음,여자,1.0,국민은행
51294,51296,66796007,렌탈,프로모션계약,대형마트A,2019-03-11,60,카드이체,DES-3A,90900,개인,43.0,경기도,경기도,계약확정,0,없음,남자,NaN,BC카드
51295,51297,66792261,렌탈,일반계약,홈쇼핑/방송,2019-03-11,60,카드이체,DES-1,96900,개인,45.0,경기도,경기도,계약확정,0,없음,여자,1.0,롯데카드
51296,51298,66579515,렌탈,프로모션계약,대형마트A,2019-03-01,60,CMS,DES-3A,96900,개인,47.0,경기도,경기도,계약확정,0,없음,남자,NaN,기업은행
51297,51299,66799558,렌탈,일반계약,대형마트A,2019-04-01,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,8.0,새마을금고

In [27]:
df1['Address1'].value_counts()

경기도      18353
경상도      12657
서울특별시     9038
충청도       4871
전라도       4698
강원도       1244
제주도        437
광주광역시        1
Name: Address1, dtype: int64

In [33]:
#렌탈 유형의 고객 데이터만 추출 , 연체건수가 5회 이상인 데이터 필터링
#연체건수가 높은 상위 10명
cond10 = (df1['Sales_Type'] == '렌탈')
cond11 = (df1['Overdue_count'] >= 5)

In [32]:
df1.loc[cond10 & cond11].sort_values(by='Overdue_count', ascending=False).head(10)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
2705,2706,66760494,렌탈,패키지계약,홈쇼핑/방송,2020-06-29,60,CMS,DES-2,81900,개인,52.0,전라도,전라도,계약확정,15,있음,남자,8.0,우리은행
5845,5846,66762531,렌탈,패키지계약,영업방판,2020-07-10,60,CMS,DES-1,134400,개인,27.0,충청도,대전광역시,계약확정,15,있음,남자,5.0,하나은행
3782,3783,66603883,렌탈,일반계약,영업방판,2019-10-28,60,CMS,DES-1,111900,개인,38.0,전라도,전라도,계약확정,15,있음,여자,7.0,농협중앙회
3094,3095,66679489,렌탈,프로모션계약,영업방판,2020-06-20,60,CMS,DES-3A,90900,개인,58.0,서울특별시,서울특별시,계약확정,15,있음,여자,4.0,우리은행
3093,3094,66679489,렌탈,프로모션계약,영업방판,2020-06-20,60,CMS,DES-3A,90900,개인,58.0,서울특별시,서울특별시,계약확정,15,있음,여자,4.0,우리은행
5594,5595,66762324,렌탈,프로모션계약,영업방판,2019-06-01,39,CMS,ERA,120900,개인,54.0,경상도,부산광역시,계약확정,15,있음,남자,8.0,부산은행
95,96,25751808,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-3A,90900,사업자,NaN,경기도,경기도,계약확정,15,있음,여자,NaN,기업은행
5846,5847,66762531,렌탈,패키지계약,영업방판,2020-07-29,60,CMS,DES-2,89400,개인,27.0,충청도,대전광역시,계약확정,15,있음,남자,5.0,하나은행
6350,6351,66763042,렌탈,프로모션계약,영업방판,2019-05-27,39,CMS,ERA,120900,개인,49.0,경상도,부산광역시,계약확정,15,있음,남자,7.0,새마을금고
347,348,66689896,렌탈,프로모션계약,영업방판,2020-07-22,60,CMS,DES-2,90900,개인,55.0,서울특별시,서울특별시,계약확정,15,있음,여자,7.0,신한은행

In [38]:
# 과제 : Payment_Type 항목이 'CMS'인 데이터만 추출해 연체건수가 높은 상위 100건의 데이터 확인

cond12 = (df1['Payment_Type'] == 'CMS')
df1.loc[cond12].sort_values(by='Overdue_count', ascending=False).head(100)

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
95,96,25751808,렌탈,프로모션계약,영업방판,2019-01-01,60,CMS,DES-3A,90900,사업자,NaN,경기도,경기도,계약확정,15,있음,여자,NaN,기업은행
2705,2706,66760494,렌탈,패키지계약,홈쇼핑/방송,2020-06-29,60,CMS,DES-2,81900,개인,52.0,전라도,전라도,계약확정,15,있음,남자,8.0,우리은행
3782,3783,66603883,렌탈,일반계약,영업방판,2019-10-28,60,CMS,DES-1,111900,개인,38.0,전라도,전라도,계약확정,15,있음,여자,7.0,농협중앙회
5594,5595,66762324,렌탈,프로모션계약,영업방판,2019-06-01,39,CMS,ERA,120900,개인,54.0,경상도,부산광역시,계약확정,15,있음,남자,8.0,부산은행
347,348,66689896,렌탈,프로모션계약,영업방판,2020-07-22,60,CMS,DES-2,90900,개인,55.0,서울특별시,서울특별시,계약확정,15,있음,여자,7.0,신한은행
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18450,18452,25740215,렌탈,일반계약,영업방판,2019-12-25,60,CMS,DES-1,96900,사업자,NaN,서울특별시,서울특별시,계약확정,13,있음,여자,NaN,기업은행
32550,32552,66782724,렌탈,일반계약,영업방판,2019-09-16,60,CMS,DES-3A,102900,개인,44.0,경상도,울산광역시,계약확정,13,있음,여자,6.0,농협회원조합
35557,35559,66785137,렌탈,프로모션계약,대형마트E,2020-01-28,60,CMS,DES-2,87900,개인,34.0,서울특별시,서울특별시,계약확정,13,있음,남자,4.0,국민은행
32184,32186,25749047,렌탈,프로모션계약,영업방판,2019-07-12,60,CMS,DES-3A,90900,사업자,NaN,충청도,대전광역시,계약확정,13,있음,여자,NaN,하나은행
46767,46769,66795654,렌탈,일반계약,영업방판,2019-02-20,60,CMS,DES-1,138900,개인,46.0,경기도,경기도,계약확정,12,있음,남자,7.0,신협중앙회